#!/bin/bash


for h in 0.906 0.907 0.908 0.909 0.91 0.911 0.912 0.913 0.914 0.915

do

mkdir t$h

cd t$h

mkdir Results

cd Results

scp ../../../../../../../../Desktop/BMN_Web/Nc16_24_mu0.5_Tc/t$h/Results/*.png ./

cd ..

scp ../../Nc16_24_mu0.5/t0.9/index.html ./

cd ..


done 

cd Obs 

cd Results

scp ../../../../../../../../Desktop/BMN_Web/Nc16_24_mu0.5_Tc/*.png ./

cd ..

cd ..

wait 

echo Done
