#!/bin/bash


for h in 0.8 0.85 0.88 0.9 0.903 0.905 0.906 0.907 0.908 0.909 0.91 0.911 0.912 0.913 0.914 0.915 0.916 0.917 0.918 0.92 0.96 1.0 1.1 1.2 1.3

do

mkdir t$h

cd t$h

mkdir Results

cd Results

scp ../../../../../../../../Desktop/BMN_Web/Nc32_24_mu2.0/t$h/Results/*.png ./

cd ..

scp ../../Nc16_24_mu0.5/t0.9/index.html ./
sed -i "s/^<title>BMN_Bosonic_Gauged.*/<title>BMN_Bosonic_Gauged\/Nc32_24_mu2.0\/t$h<\/title>/" index.html
sed -i "s/^<h1>BMN_Bosonic_Gauged.*/<h1>BMN_Bosonic_Gauged\/Nc32_24_mu2.0\/t$h<\/h1>/" index.html

cd ..


done 

cd Obs 

cd Results

scp ../../../../../../../../Desktop/BMN_Web/Nc32_24_mu2.0/*.png ./

cd ..

cd ..

wait 

echo Done
