#!/bin/bash


for rt in 0.2 0.25 0.3 0.35 0.4 0.5 0.6 0.8 1.0 1.2 1.4

do

for g in 0.30 0.40 0.50

do

rm -r rt$rt\_g$g
mkdir rt$rt\_g$g
cd rt$rt\_g$g
scp ../index.html ./
#rm -r Results
mkdir Results
cd Results

scp /home/user/Desktop/SUSY_2D-BOUND/susy_bound_results/Nc12_24nt12/rt$rt\_g$g/Results/*.png ./



cd ..

sed -i -e "s/rt0.5\_g0.30/rt$rt\_g$g/g" index.html
sed -i -e "s/24nt24/24nt12/g" index.html

cd ..

done 

done


cd Plots

rm *.pdf
scp /home/user/Desktop/SUSY_2D-BOUND/susy_bound_results/Nc12_24nt12/*.pdf ./

echo Done
