#!/bin/bash


for h in 0.8 0.85 0.91 0.93 0.935 0.937 0.94 0.943 0.945 0.947 0.949 0.95 0.953 0.955 0.96 0.98 1.0 1.1 1.2 1.3

do

mkdir t$h

cd t$h

mkdir Results

cd Results

scp ../../../../../../../../Desktop/BMN_Web/Nc32_24_mu4.0/t$h/Results/*.png ./

cd ..

scp ../../Nc16_24_mu0.5/t0.9/index.html ./
sed -i "s/^<title>BMN_Bosonic_Gauged.*/<title>BMN_Bosonic_Gauged\/Nc32_24_mu4.0\/t$h<\/title>/" index.html
sed -i "s/^<h1>BMN_Bosonic_Gauged.*/<h1>BMN_Bosonic_Gauged\/Nc32_24_mu4.0\/t$h<\/h1>/" index.html

cd ..


done 

cd Obs 

cd Results

scp ../../../../../../../../Desktop/BMN_Web/Nc32_24_mu4.0/*.png ./

cd ..

cd ..

wait 

echo Done
