#!/bin/bash


for rt in 1.25

do

for g in 0.10 0.20 0.30 0.40 0.50

do

rm -r rt$rt\_g$g
mkdir rt$rt\_g$g
cd rt$rt\_g$g
scp ../index.html ./
#rm -r Results
mkdir Results
cd Results

scp /home/user/Desktop/SUSY_2D-BOUND/susy_bound_results/Nc12_24nt24/rt$rt\_g$g/Results/*.png ./



cd ..

sed -i -e "s/rt0.5\_g0.30/rt$rt\_g$g/g" index.html

cd ..

done 

done


cd Plots

scp /home/user/Desktop/SUSY_2D-BOUND/susy_bound_results/Nc12_24nt24/*.pdf ./

echo Done
