#!/bin/bash


for h in 1.12 1.13 1.14 1.1425 1.145 1.1475 1.15 1.1525 1.155 1.1575 1.16 1.17 1.18  

do

mkdir t$h

cd t$h

mkdir Results

cd Results

scp ../../../../../../../../Desktop/BMN_Web/Nc16_24_mu9.0/t$h/Results/*.png ./

cd ..

scp ../../Nc16_24_mu0.5/t0.9/index.html ./
sed -i "s/^<title>BMN_Bosonic_Gauged.*/<title>BMN_Bosonic_Gauged\/Nc16_24_mu9.0\/t$h<\/title>/" index.html
sed -i "s/^<h1>BMN_Bosonic_Gauged.*/<h1>BMN_Bosonic_Gauged\/Nc16_24_mu9.0\/t$h<\/h1>/" index.html

cd ..


done 

cd Obs 

cd Results

scp ../../../../../../../../Desktop/BMN_Web/Nc16_24_mu9.0/*.png ./

cd ..

cd ..

wait 

echo Done
