#!/bin/bash


for h in 0.2 0.25 0.3 0.35 0.4 0.45 0.8 0.85 0.89 0.892 0.894 0.896 0.897 0.898 0.899 0.9 0.901 0.902 0.903 0.905 0.91 0.95 1.0 1.1 1.2 1.3

do

mkdir t$h

cd t$h

mkdir Results

cd Results

scp ../../../../../../../../Desktop/BFSS_Results/Nc32_24/f$h/Results/*.png ./

cd ..

scp ../../Nc16_24_mu0.5/t0.9/index.html ./
sed -i "s/^<title>BMN_Bosonic_Gauged.*/<title>BFSS_Bosonic_Gauged\/Nc32_24\/t$h<\/title>/" index.html
sed -i "s/^<h1>BMN_Bosonic_Gauged.*/<h1>BFSS_Bosonic_Gauged\/Nc32_24\/t$h<\/h1>/" index.html

cd ..


done 

cd Obs 

cd Results

scp ../../../../../../../../Desktop/BFSS_Results/Nc32_24/*.png ./

cd ..

cd ..

wait 

echo Done
