#!/bin/bash


for rt in 0.6 0.7 0.75 0.8 0.85 0.9 0.95 1.0 1.1 1.2 1.3 1.6

do

for g in 0.30

do

rm -r rt$rt\_g$g
mkdir rt$rt\_g$g
cd rt$rt\_g$g
scp ../index.html ./
#rm -r Results
mkdir Results
cd Results

scp /home/user/Desktop/SUSY_2D-BOUND/susy_bound_results/Nc20_12nt12/rt$rt\_g$g/Results/*.png ./



cd ..

sed -i -e "s/rt0.5\_g0.30/rt$rt\_g$g/g" index.html
sed -i -e "s/Nc12\_24nt24/Nc20\_12nt12/g" index.html

cd ..

done 

done


cd Plots

rm *.pdf
scp /home/user/Desktop/SUSY_2D-BOUND/susy_bound_results/Nc20_12nt12/*.pdf ./

echo Done
