#!/bin/bash


for rt in 0.6 0.8 0.9 0.95 1.0 1.05 1.1 1.2 1.4 1.6 1.8 2.0

do

for g in 0.30 0.40 0.50

do

rm -r rt$rt\_g$g
mkdir rt$rt\_g$g
cd rt$rt\_g$g
scp ../index.html ./
#rm -r Results
mkdir Results
cd Results

scp /home/user/Desktop/SUSY_2D-BOUND/susy_bound_results/Nc12_12nt24/rt$rt\_g$g/Results/*.png ./



cd ..

sed -i -e "s/rt0.5\_g0.30/rt$rt\_g$g/g" index.html
sed -i -e "s/24nt24/12nt24/g" index.html

cd ..

done 

done


cd Plots

rm *.pdf
scp /home/user/Desktop/SUSY_2D-BOUND/susy_bound_results/Nc12_12nt24/*.pdf ./

echo Done
