#!/bin/bash


for rt in 0.05 0.075 0.1 0.125 0.15 0.175 0.2

do

for g in 0.60 0.70 0.80

do

rm -r rt$rt\_g$g
mkdir rt$rt\_g$g
cd rt$rt\_g$g

scp /home/hp/Desktop/Nc12_24nt6/rt$rt\_g$g/index.html ./
scp -r /home/hp/Desktop/Nc12_24nt6/rt$rt\_g$g/data ./


cd ..


done 

done

for rt in 0.15

do

for g in 0.50 0.40

do

rm -r rt$rt\_g$g
mkdir rt$rt\_g$g
cd rt$rt\_g$g

scp /home/hp/Desktop/Nc12_24nt6/rt$rt\_g$g/index.html ./
scp -r /home/hp/Desktop/Nc12_24nt6/rt$rt\_g$g/data ./


cd ..


done 

done

echo Done
